MOVE_HINT = "WASD/стрелки: движение"
ATTACK_HINT = "Пробел: атака"
INTERACT_HINT = "E: взаимодействие"
MAP_HINT = "M: карта"
PAUSE_HINT = "Esc: пауза"
FULLSCREEN_HINT = "F11: полноэкранный режим"

ATTACK_READY = "Атака: готова"
ATTACK_COOLDOWN = "Атака: {seconds:.1f}с"

HP_LABEL = "Здоровье"
SCENE_LABEL = "Сцена"
REGION_INFLUENCE_PLAYER = "Влияние игрока"
REGION_INFLUENCE_ENEMY = "Влияние врага"
ASSAULT_READY = "Штурм доступен"
ASSAULT_LOCKED = "Штурм закрыт"
REGION_LIBERATED = "Регион освобождён"

CASTLE_ASSAULT_START = "C: начать штурм замка"
OUTPOST_CLEAR_PROGRESS = "Зачистка аванпоста: {percent}%"
OUTPOST_HOLD_TO_CLEAR = "Удерживай E: зачистить аванпост"
OUTPOST_CLEAR_ENEMIES = "Сначала убей врагов у аванпоста"
OUTPOST_CLEARED = "Аванпост зачищен"

NPC_REPORT_PROGRESS = "Отчёт NPC: {percent}%"
NPC_HOLD_TO_REPORT = "Удерживай E: доложить NPC"
NPC_CLEAR_OUTPOST_FIRST = "Сначала зачисти аванпост"
NPC_QUEST_COMPLETED = "Задание выполнено"

DEFEATED_RECOVER = "Поражение. Нажми R, чтобы восстановиться."
DEFEATED_RESTART = "Поражение. Нажми R, чтобы начать штурм заново."
ASSAULT_COMPLETED = "Регион освобождён. Нажми M, чтобы вернуться на карту."

NEW_GAME = "Новая игра"
CONTINUE = "Продолжить"
CONTINUE_UNAVAILABLE = "Продолжить (недоступно)"
SETTINGS_UNAVAILABLE = "Настройки (недоступны)"
EXIT = "Выход"
NEW_GAME_CONFIRM_TITLE = "Начать новую игру?"
NEW_GAME_CONFIRM_WARNING = "Текущий прогресс будет удалён."
NEW_GAME_CONFIRM_YES = "Да, удалить прогресс"
NEW_GAME_CONFIRM_NO = "Нет, вернуться"
RESUME = "Продолжить"
WORLD_MAP = "Карта регионов"
MAIN_MENU = "Главное меню"
PAUSED = "Пауза"
SELECT_HINT = "Enter/клик: выбрать"

WORLD_MAP_ENTER_REGION = "Enter/клик: войти в регион"
WORLD_MAP_LOCKED = "Закрыто"
WORLD_MAP_START_ASSAULT = "C: начать штурм"
WORLD_MAP_BACK = "Esc/M: назад"
CONTROL_LABEL = "Контроль"
INFLUENCE_STATUS = "Влияние: игрок {player} / враг {enemy}"
CONTROL_PLAYER = "игрок"
CONTROL_ENEMY = "враг"
CONTROL_LOCKED = "закрыто"
